version: '3.8'
services:
  tracker:
    build: .
    ports:
      - "8000:8000"
    command: python src/main.py tracker --tracker_addr='0.0.0.0' --tracker_port=8000

  webserver:
    build: .
    ports:
      - "8080:8080"
    command: python src/main.py webserver --server_port=8080 --tracker_addr='tracker' --tracker_port=8000 --interval=1
    depends_on:
      - tracker

  node1:
    build: .
    expose:
      - "6000"
      - "9000"
    command: python src/main.py node --p2p_port=6000 --node_port=9000 --tracker_addr='tracker' --tracker_port=8000 --heartbeat_interval=1
    depends_on:
      - tracker

  node2:
    build: .
    expose:
      - "6000"
      - "9000"
    command: python src/main.py node --p2p_port=6000 --node_port=9000 --tracker_addr='tracker' --tracker_port=8000 --heartbeat_interval=1
    depends_on:
      - tracker
      - node1
